svi_profiles:
  GENERIC:
    mtu: 1560
    enabled: true
  GENERIC_FULL:
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  WITH_NO_MTU:
    enabled: true
  WITH_SNOOPING:
    enabled: true
    igmp_snooping_enabled: false

tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Picard:
    mac_vrf_vni_base: 10000
    vrfs:
      Riker:
        vrf_vni: 10
        svis:
          10:
            name: VLAN_10
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          20:
            name: VLAN_20
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.20.1/24    