CVP_CONFIGLETS:
  AVD_leaf1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf2_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel3\n   description\
    \ SPINES_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 3\n!\ninterface Ethernet1\n   description\
    \ MLAG_PEER_leaf2_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n\
    !\ninterface Ethernet2\n   description MLAG_PEER_leaf2_Ethernet2\n   no shutdown\n\
    \   channel-group 1 mode active\n!\ninterface Ethernet3\n   description SPINE1_Ethernet2\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ SPINE2_Ethernet2\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.0/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id rack1\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.1\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_leaf2: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf2\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf1_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel3\n   description\
    \ SPINES_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 3\n!\ninterface Ethernet1\n   description\
    \ MLAG_PEER_leaf1_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n\
    !\ninterface Ethernet2\n   description MLAG_PEER_leaf1_Ethernet2\n   no shutdown\n\
    \   channel-group 1 mode active\n!\ninterface Ethernet3\n   description SPINE1_Ethernet3\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ SPINE2_Ethernet3\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.1/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id rack1\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.0\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_leaf3: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf3\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf4_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel3\n   description\
    \ SPINES_Po4\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 3\n!\ninterface Ethernet1\n   description\
    \ MLAG_PEER_leaf4_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n\
    !\ninterface Ethernet2\n   description MLAG_PEER_leaf4_Ethernet2\n   no shutdown\n\
    \   channel-group 1 mode active\n!\ninterface Ethernet3\n   description SPINE1_Ethernet4\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ SPINE2_Ethernet4\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.4/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id rack2\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.5\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_leaf4: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf4\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf3_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel3\n   description\
    \ SPINES_Po4\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 3\n!\ninterface Ethernet1\n   description\
    \ MLAG_PEER_leaf3_Ethernet1\n   no shutdown\n   channel-group 1 mode active\n\
    !\ninterface Ethernet2\n   description MLAG_PEER_leaf3_Ethernet2\n   no shutdown\n\
    \   channel-group 1 mode active\n!\ninterface Ethernet3\n   description SPINE1_Ethernet5\n\
    \   no shutdown\n   channel-group 3 mode active\n!\ninterface Ethernet4\n   description\
    \ SPINE2_Ethernet5\n   no shutdown\n   channel-group 3 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.5/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id rack2\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.4\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_spine1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname spine1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 4096\n!\nno enable password\nno aaa\
    \ root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_spine2_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ RACK1_Po3\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel4\n   description\
    \ RACK2_Po3\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 4\n!\ninterface Ethernet1\n   description MLAG_PEER_spine2_Ethernet1\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ LEAF1_Ethernet3\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet3\n   description LEAF2_Ethernet3\n   no shutdown\n   channel-group\
    \ 2 mode active\n!\ninterface Ethernet4\n   description LEAF3_Ethernet3\n   no\
    \ shutdown\n   channel-group 4 mode active\n!\ninterface Ethernet5\n   description\
    \ LEAF4_Ethernet3\n   no shutdown\n   channel-group 4 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.0/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id SPINES\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.1\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_spine2: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname spine2\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 4096\n!\nno enable password\nno aaa\
    \ root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_spine1_Po1\n   no\
    \ shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ RACK1_Po3\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel4\n   description\
    \ RACK2_Po3\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 4\n!\ninterface Ethernet1\n   description MLAG_PEER_spine1_Ethernet1\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ LEAF1_Ethernet4\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet3\n   description LEAF2_Ethernet4\n   no shutdown\n   channel-group\
    \ 2 mode active\n!\ninterface Ethernet4\n   description LEAF3_Ethernet4\n   no\
    \ shutdown\n   channel-group 4 mode active\n!\ninterface Ethernet5\n   description\
    \ LEAF4_Ethernet4\n   no shutdown\n   channel-group 4 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.99.1/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id SPINES\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.99.0\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
CVP_TOPOLOGY:
  ATL_L2LS:
    parent_container: ATL_L2LS_FABRIC
  ATL_L2LS_FABRIC:
    parent_container: Tenant
  L2LS_LEAFS:
    parent_container: ATL_L2LS
  L2LS_SPINES:
    devices:
    - spine1
    - spine2
    parent_container: ATL_L2LS
  rack1:
    devices:
    - leaf1
    - leaf2
    parent_container: L2LS_LEAFS
  rack2:
    devices:
    - leaf3
    - leaf4
    parent_container: L2LS_LEAFS
changed: false
