---
# deploy.yml

- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: provision CVP with AVD configuration
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ATL_L2LS_FABRIC'
        configlets_prefix: 'AVD'
        # device_filter: 'DC1'
        state: present