---
# build.yml

- name: Build Configs
  hosts: ATL_L2LS_FABRIC
  gather_facts: false
  tasks:

    - name: Generate AVD Structured Configurations and Fabric Documentation
      import_role:
        name: arista.avd.eos_designs

    - name: Generate Device Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen
